format: 
  revealjs:
#    header: |
#      <button onclick="window.location = location.href.replace('/en/','/es/');" class="btn"><i class="fa fa-language"></i> Espagnol</button>
    scrollable: true
    margin: 0
    code-overflow: wrap
    reference-location: document
    widescreen: true
    center: true
    transition: slide
    self_contained: false
    reveal_options:
        slideNumber: true
        previewLinks: false
        chalkboard:
          theme: chalkboard
          toggleNotesButton: true
    reveal_plugins: ["chalkboard"]
filters:
  - reveal-header
website:
  body-header: |
    <button onclick="window.location = location.href.replace('/en/','/es/');" class="btn"><i class="fa fa-language"></i> Espagnol</button>

profile:
  default: english
  group: [english, espagnol]