---
title: "Reproducibility when data are confidential"
author: 
  - "Lars Vilhuber"
date: 2026-06-11
---


```{r config,include=FALSE}

library(qrcode)
# The repository name

message(Sys.getenv("GITHUB_REPOSITORY"))

# Process the repository name to generate the URL
# - split the two components
# - combine them into a URL with 'github.io' in the middle

SUBDIRECTORY <- "presentation" # Leave this empty if this file is in the main directory of the repository

GITHUB_REPOSITORY <- Sys.getenv("GITHUB_REPOSITORY")
GITHUB_REPOSITORY_PARTS <- strsplit(GITHUB_REPOSITORY, "/")[[1]]
REPOSITORY_URL <- paste0("https://github.com/", GITHUB_REPOSITORY)

WEBSITE_URL <- paste0("https://", GITHUB_REPOSITORY_PARTS[1], ".github.io/", GITHUB_REPOSITORY_PARTS[2], "/", SUBDIRECTORY)
WEBSITE_SHORT <- paste0(GITHUB_REPOSITORY_PARTS[1], ".github.io/", GITHUB_REPOSITORY_PARTS[2], "/", SUBDIRECTORY)

```


```{r, child=c(here::here('00-qrcode.md'))}
```

```{r, child=c(here::here('00-follow-along.md'))}
```

```{r, child=c(here::here('00-intro.md'))}
```

# What are the goals


```{r, child=c(here::here('01-goals-public.md'))}
```

```{r, child=c(here::here('01-goals-private.md'))}
```

```{r, child=c(here::here('02-what-is-confidential-data.md'))}
```



# How to achieve the goals

```{r, child=c(here::here('03-file-organization.md'))}
```

```{r, child=c(here::here('03-target.md'))}
```

```{r, child=c(here::here('03-versioning.md'))}
```

```{r, child=c(here::here('02-01-readme-notebook.md'))}
```

```{r, child=c(here::here('04-code-raw-to-output.md'))}
```

```{r, child=c(here::here('04-provenance.md'))}
```

```{r, child=c(here::here('16-survey-extract.md'))}
```

```{r, child=c(here::here('02-03-provenance-private.md'))}
```


```{r, child=c(here::here('05-disclosure-avoidance.md'))}
```

```{r, child=c(here::here('06-secrets-in-code.md'))}
```

```{r, child=c(here::here('07-software.md'))}
```


```{r, child=c(here::here('09-confidential-data-packaging.md'))}
```

```{r, child=c(here::here('99-wrapping-up.md'))} 
```

# Appendix

```{r, child=c(here::here('interactive-exercise-1.md'))}
```

```{r, child=c(here::here('interactive-exercise-2.md'))}
```

```{r, child=c(here::here('12-environments-in-stata.md'))} 
```

```{r, child=c(here::here('99-links.md'))}
```