name: deploy-presentation

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:

  compile-presentation:
    runs-on: ubuntu-22.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v3
  
    # Let's do the Quarto
    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'

    - name: Install R Dependencies 
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 1
        
    - name: Render Quarto Project
      env:
        QUARTO_PRINT_STACK: true
    #   uses: quarto-dev/quarto-actions/render@v2
    #   with:
    #     path: ./presentation
      run: |
        quarto render  index.Rmd --output-dir _html

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3.0.1    
      with:
        path: _html
    
  publish:
    needs: compile-presentation
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 