name: Create website
on: 
  push:
    branches: 
      - main
  
jobs:
  create-website:
    runs-on: ubuntu-latest
    env: 
        CENSUS_API_KEY: ${{ secrets.CENSUS_API_KEY }}
    if: "!contains(github.event.head_commit.message, '[skipci]')"
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - name: Make executable
        run: "chmod +x ./_build.sh"
      # Runs a set of commands using the runners shell
      - name: Run docker for R 
        uses: docker://larsvilhuber/reproducibility-confidential:latest
        with:
          args: "/github/workspace/_build.sh "
          
          
      # send it to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: .
           user_name: 'Github Action Bot'
           user_email: 'lars.vilhuber@cornell.edu'
           publish_branch: gh-pages 
           keep_files: true
